import { Constants } from "../misc/Constants"
const CONSTANTS = Constants['polygon'];

module.exports = [
  OWNER_ADDRESS,
  CONSTANTS.HOST_SUPERFLUID_ADDRESS,
  CONSTANTS.CFA_SUPERFLUID_ADDRESS,
  CONSTANTS.IDA_SUPERFLUID_ADDRESS,
  CONSTANTS.RIC_TOKEN_ADDRESS,
  CONSTANTS.SF_REG_KEY,
  CONSTANTS.REX_REFERRAL_ADDRESS

];
