name: Lint

on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Prettier check
        run: npm run prettier:solidity && npm run prettier:ts
